config/routes.rb
Rails.application.routes.draw do

  resources :news
  resources :subscriptions
  get 'welcome/index'

  devise_for :users, controllers: { registrations: "users/registrations"}

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord

    def self.send_daily
        subs = Subscription.where(time: 'daily')
        subs.each do |sub|
            DailyMailingJob.perform_later(sub.email)
        end
    end

    def self.send_weekly
        subs = Subscription.where(time: 'weekly')
        subs.each do |sub|
            DailyMailingJob.perform_later(sub.email)
        end
    end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:destroy] #:show, :edit, :update, 

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @dailySubscription = Subscription.where(email: current_user.email, time: 'daily')
    @weeklySubscription = Subscription.where(email: current_user.email, time: 'weekly')

    @isSignedDaily = @dailySubscription.count > 0
    @isSignedWeekly = @weeklySubscription.count > 0
    
    if not @isSignedDaily or not @isSignedWeekly
      @subscription = Subscription.new
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
  #  @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscriptions_url, notice: t('subscription.notice.created') }
        format.json { render :show, status: :created, location: @subscription }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: t('subscription.notice.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email, :time)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      ul
        - @subscription.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :time
    = f.text_field :time
  .actions = f.submit

app/views/subscriptions/edit.html.slim
h1 Editing subscription

== render 'form'

=> link_to 'Show', @subscription
'|
=< link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.slim
div.row.h1 = t('subscription.title')

-if notice
    div.row.alert.alert-success
         = notice

div.row.alert.alert-success
  - if @isSignedDaily
    div.col-md
      = t('subscription.info.sub_daily')
    div.col-sm.text-right
      - @dailySubscription.each do |subscription|
        = button_to t('subscription.unsubscribe'),
                    subscription, 
                    class: "btn btn-danger", 
                    data: { confirm: t('questions.are_you_sure')},
                    method: :delete
  - else
    div.col-md
      = t('subscription.info.unsub_daily')
    div.col-sm.text-right
      = form_for @subscription do |f|
        = f.hidden_field :email, value: current_user.email
        = f.hidden_field :time, value: 'daily'
        .actions = f.submit t('subscription.subscribe'), class: "btn btn-success"

div.row.alert.alert-success
  - if @isSignedWeekly
    div.col-md
      = t('subscription.info.sub_weekly')
    div.col-sm.text-right
      - @weeklySubscription.each do |subscription|
        = button_to t('subscription.unsubscribe'),
                    subscription, 
                    class: "btn btn-danger", 
                    data: { confirm: t('questions.are_you_sure')},
                    method: :delete
  - else
    div.col-md
      = t('subscription.info.unsub_weekly')
    div.col-sm.text-right
      = form_for @subscription do |f|
        = f.hidden_field :email, value: current_user.email
        = f.hidden_field :time, value: 'weekly'
        .actions = f.submit t('subscription.subscribe'), class: "btn btn-success"

app/views/subscriptions/new.html.slim
h1 New subscription

== render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.slim
p#notice = notice

p
  strong Email:
  = @subscription.email
p
  strong Type:
  = @subscription.time

=> link_to 'Edit', edit_subscription_path(@subscription)
'|
=< link_to 'Back', subscriptions_path